---
title: "Métodos Numéricos Aplicados a Finanças --- Turma 2025"
author: "Prof. Frega"
date: "11/03/2025"
output:
  bookdown::html_document2:
    toc: yes
    toc_depth: 6
    toc_float: yes
    theme: cer
    number_sections: yes
    code_folding: show
    css: estilo.css
  html_document:
    toc: yes
    toc_depth: '6'
    df_print: paged
  rmdformats::readthedown:
    toc_depth: 6
    number_sections: yes
    code_folding: show
  pdf_document:
    toc: yes
    toc_depth: 6
    number_sections: yes
    extra_dependencies:
      babel: portuguese,brazil
      geometry: top=3cm, bottom=2cm,left=3cm,right=2cm
subtitle: Todas as aulas
documentclass: book
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy=TRUE, tidy.opts = list(blank = FALSE, width.cutoff = 60), fig.width = 5, fig.align = "center", wrapper=TRUE)
knitr::knit_hooks$set(wrapper = function(before, options) {
  # the original chunk might be indented
  if (is.null(indent <- options$indent)) indent <- ''
  
  # hide the wrapper=TRUE option
  opts <- gsub(', wrapper=TRUE', '', options$params.src)
  
  if (before) {
    # add the header
    sprintf('\n\n%s````\n```{r,%s}\n````\n', indent, opts)
  } else {
    # add the footer
    sprintf('\n\n%s````\n```\n````\n', indent)
  }
})
library(magrittr)
library(reticulate)
```

# AULA 1 { - }

```{r Aula 01, child="Aula01.Rmd"}

```

# AULA 2 { - }

```{r Aula 02, child="Aula02.Rmd"}

```

# AULA 3 { - }

```{r Aula 03, child="Aula03.Rmd"}

```

