---
title: "Métodos Numéricos Aplicados a Finanças --- Turma 2025"
subtitle: "Aula 03"
author: "Prof. Frega 
<br>\\cr
\\small <small>PPGOLD/Universidade Federal do Paraná</small>"
date: "25/03/2025"
output: 
  # html_document:
  # o tipo de documento bookdown::html_document2 acrescenta algumas 
  # funcionalidades extras ao tipo html_document
  bookdown::html_document2: 
    # mostra o sumário com seu nível máximo
    toc: yes
    toc_depth: 6
    # coloca o sumário flutuante à esquerda
    toc_float: true
    theme: cer
    number_sections: yes
    # mostra/oculta os chunks de código
    code_folding: 'show'
    css: estilo.css
  rmdformats::readthedown:
    toc_depth: 6
    number_sections: yes
    # mostra/oculta os chunks de código
    code_folding: 'show'
  pdf_document:
    toc: yes
    toc_depth: 6
    number_sections: yes
    extra_dependencies:
      babel: ["portuguese,brazil"]
      geometry: ["top=3cm, bottom=2cm,left=3cm,right=2cm"]
documentclass: book
---

```{=html}
```

```{r}
library(magrittr)
```

## Forecasting (Predicting a Particular Value)

```{r}
library(PoEdata)
data("food")
plot(x = food$income, y = food$food_exp, xlim = c(0, max(food$income)), ylim = c(0, max(food$food_exp)), axes = FALSE); axis(1, pos=0); axis(2,pos=0)
alpha <- 0.05
x <- 20
xbar <- mean(food$income)
ybar <- mean(food$food_exp)
m1 <- lm(formula = food_exp~income, data=food)
abline(m1); points(xbar, ybar, col = "red", pch = 16, cex = 2); abline(h = ybar, v = xbar, col = "red", lty = 2)
predict(m1, data.frame(income = 20), interval="confidence",level=0.95)
predict(m1, data.frame(income = 20), interval="prediction",level=0.95)
summary(m1) -> sm1; sm1
xx = seq(min(food$income), max(food$income), length.out = 50)
yy = predict(m1, data.frame(income=xx), interval = "prediction", level = 1-0.05)
lines(xx, yy[,2], col = "blue", lty = 3); lines(xx, yy[,3], col = "blue", lty = 3)
```

$$
\text{food_exp}= b_0+b_1\ \text{income}+e\\
\widehat{\text{food_exp}}= 83.416+10.210\ \text{income}
$$

## Goodness-of-Fit

Bondade de ajuste

```{r}
sm1
sm1$r.squared
sm1$adj.r.squared
sm1$fstatistic
```

## Linear-Log Models


```{r}
mod2 <- lm(food_exp~log(income), data=food)
summary(mod2)
```

## Residuals and Diagnostics

### Normalidade dos resíduos

```{r}
# resíduos padronizados tem média zero e desvio-padrão um
m1$residuals %>% scale -> padres
padres %>% hist(freq = FALSE)
curve(dnorm(x, 0, 1), xlim = c(-3, 3), add = TRUE)
```

```{r}
# teste de Shapiro-Wilk
# H0: não há desvios da normalidade (p > 0.05)
padres %>% shapiro.test()
```

```{r}
library(tseries)
# Teste de Jarque-Bera 
# H0: não há desvios da normalidade (p > 0.05)
padres %>% jarque.bera.test()
```
Testes de normalidade funcionam bem para n > 30 e n < 400 (valores empíricos e aproximados).


```{r}
library(car)
padres %>% qqPlot()
```

```{r}
set.seed(1)
rexp(20) %>% qqPlot
runif(20) %>% qqPlot
```








